export const projects = [
  {
    id: 3,
    href: "https://apex-performance-demo.onrender.com/",
    image: "/assets/projects/apex/apex-dashboard.png",
    bgImage: "/assets/projects/apex/apex-dashboard.png",
    images: [
      "/assets/projects/apex/apex-dashboard.png",
      "/assets/projects/apex/apex-ejercicios.png",
      "/assets/projects/apex/apex-analitica.png",
      "/assets/projects/apex/apex-rutinas.png",
      "/assets/projects/apex/apex-peso.png",
      "/assets/projects/apex/apex-registro.png",
      "/assets/projects/apex/apex-demo-access.png",
    ],
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "JavaScript" },
      { id: 3, name: "Tailwind CSS" },
      { id: 4, name: "TanStack React Query" },
      { id: 5, name: "OpenAI Images API" },
      { id: 6, name: "Cloudinary" },
      { id: 7, name: "Node.js" },
      { id: 8, name: "Express" },
      { id: 9, name: "MongoDB" },
      { id: 10, name: "Vitest / RTL" },
      { id: 11, name: "Jest / Supertest" },
      { id: 12, name: "Playwright / Cypress" },
    ],
  },
  {
    id: 1,
    href: "https://pos-frontend-bajm.onrender.com/",
    image: "/assets/projects/pos-1.jpeg",
    bgImage: "/assets/backgrounds/blanket.jpg",
    images: [
      "/assets/projects/pos-1.jpeg",
      "/assets/projects/pos-2.jpeg",
      "/assets/projects/pos-3.jpeg",
      "/assets/projects/pos-4.jpeg",
      "/assets/projects/pos-5.jpeg",
      "/assets/projects/pos-6.jpeg",
      "/assets/projects/pos-7.jpeg",
      "/assets/projects/pos-8.jpeg",
      "/assets/projects/pos-9.jpeg",
    ],
    frameworks: [
      { id: 1, name: "React" },
      { id: 2, name: "Node.js" },
      { id: 3, name: "Express" },
      { id: 4, name: "MongoDB" },
      { id: 5, name: "Firebase" },
      { id: 6, name: "Figma" },
    ],
  },
  {
    id: 2,
    href: "https://pchuquimia.github.io/TetrisGame/",
    image: "/assets/projects/tetris-1.jpeg",
    bgImage: "",
    images: [
      "/assets/projects/tetris-1.jpeg",
      "/assets/projects/tetris-2.jpeg",
    ],
    frameworks: [
      { id: 1, name: "JavaScript" },
      { id: 2, name: "HTML5 Canvas" },
      { id: 3, name: "CSS3" },
    ],
  },
];
export const socials = [
  { key: "linkedin", href: "https://www.linkedin.com/in/pchuquimia/" },
  { key: "github", href: "https://github.com/pchuquimia" },
  { key: "apex", href: "https://apex-performance-demo.onrender.com/" },
  { key: "email", href: "mailto:pablo.ivan.chuquimia@gmail.com" },
  { key: "phone", href: "tel:+59179573025" },
  { key: "cvEs", href: "/cv/Pablo_Chuquimia_CV_Frontend_ES.pdf" },
  { key: "cvEn", href: "/cv/Pablo_Chuquimia_CV_Frontend_EN.pdf" },
];
